
export interface ChapterData {
  binaryCode: string;
  name: string;
}

export interface SubjectData {
  id: '1B0' | '2P0' | '3C0';
  name: 'Biology' | 'Physics' | 'Chemistry';
  chapters: ChapterData[];
}

export const QUIZ_SUBJECTS: SubjectData[] = [
  {
    id: '1B0',
    name: 'Biology',
    chapters: [
      { binaryCode: '000000', name: 'Structural Organisation in Animals' },
      { binaryCode: '000001', name: 'Biomolecules' },
      { binaryCode: '000010', name: 'Breathing and Exchange of Gases' },
      { binaryCode: '000011', name: 'Body Fluids and Circulation' },
      { binaryCode: '000100', name: 'Excretory Products and their Elimination' },
      { binaryCode: '000101', name: 'Locomotion and Movement' },
      { binaryCode: '000110', name: 'Neural Control and Coordination' },
      { binaryCode: '000111', name: 'Chemical Coordination and Integration' },
      { binaryCode: '001000', name: 'Animal Kingdom' },
      { binaryCode: '001001', name: 'Human Reproduction' },
      { binaryCode: '001010', name: 'Reproductive Health' },
      { binaryCode: '001011', name: 'Evolution' },
      { binaryCode: '001100', name: 'Human Health and Disease' },
      { binaryCode: '001101', name: 'Biotechnology – Principles and Processes' },
      { binaryCode: '001110', name: 'Biotechnology and its Applications' },
      { binaryCode: '001111', name: 'Animal Tissue' },
      { binaryCode: '010000', name: 'Cell – The Unit of Life' },
      { binaryCode: '010001', name: 'Cell Cycle and Cell Division' },
      { binaryCode: '010010', name: 'Principles of Inheritance and Variation' },
      { binaryCode: '010011', name: 'Molecular Basis of Inheritance' },
      { binaryCode: '010100', name: 'The Living World' },
      { binaryCode: '010101', name: 'Biological Classification' },
      { binaryCode: '010110', name: 'Microbes in Human Welfare' },
      { binaryCode: '010111', name: 'Plant Kingdom' },
      { binaryCode: '011000', name: 'Morphology of Flowering Plants' },
      { binaryCode: '011001', name: 'Anatomy of Flowering Plants' },
      { binaryCode: '011010', name: 'Sexual Reproduction in Flowering Plants' },
      { binaryCode: '011011', name: 'Respiration in Plants' },
      { binaryCode: '011100', name: 'Photosynthesis in Higher Plants' },
      { binaryCode: '011101', name: 'Plant Growth and Development' },
      { binaryCode: '011110', name: 'Organisms and Population' },
      { binaryCode: '011111', name: 'Ecosystem' },
      { binaryCode: '100000', name: 'Biodiversity and Conservation' },
    ],
  },
  {
    id: '2P0',
    name: 'Physics',
    chapters: [
      { binaryCode: '000000', name: 'Units and Measurements' },
      { binaryCode: '000001', name: 'Mathematical Tools' },
      { binaryCode: '000010', name: 'Motion in a Straight Line' },
      { binaryCode: '000011', name: 'Motion in a Plane' },
      { binaryCode: '000100', name: 'Laws of Motion' },
      { binaryCode: '000101', name: 'Work, Energy and Power' },
      { binaryCode: '000110', name: 'Centre of Mass & System of Particles' },
      { binaryCode: '000111', name: 'Rotational Motion' },
      { binaryCode: '001000', name: 'Gravitation' },
      { binaryCode: '001001', name: 'Mechanical Properties of Solids' },
      { binaryCode: '001010', name: 'Mechanical Properties of Fluids' },
      { binaryCode: '001011', name: 'Thermal Properties of Matter' },
      { binaryCode: '001100', name: 'Kinetic Theory' },
      { binaryCode: '001101', name: 'Thermodynamics' },
      { binaryCode: '001110', name: 'Oscillations' },
      { binaryCode: '001111', name: 'Waves' },
      { binaryCode: '010000', name: 'Electric Charges and Fields' },
      { binaryCode: '010001', name: 'Electrostatic Potential and Capacitance' },
      { binaryCode: '010010', name: 'Current Electricity' },
      { binaryCode: '010011', name: 'Moving Charges and Magnetism' },
      { binaryCode: '010100', name: 'Magnetism and Matter' },
      { binaryCode: '010101', name: 'Electromagnetic Induction' },
      { binaryCode: '010110', name: 'Alternating Current' },
      { binaryCode: '010111', name: 'Electromagnetic Waves' },
      { binaryCode: '011000', name: 'Ray Optics and Optical Instruments' },
      { binaryCode: '011001', name: 'Wave Optics' },
      { binaryCode: '011010', name: 'Dual Nature of Radiation and Matter' },
      { binaryCode: '011011', name: 'Atoms' },
      { binaryCode: '011100', name: 'Nuclei' },
      { binaryCode: '011101', name: 'Semiconductor Electronics' },
    ],
  },
  {
    id: '3C0',
    name: 'Chemistry',
    chapters: [
      { binaryCode: '000000', name: 'Some Basic Concepts of Chemistry' },
      { binaryCode: '000001', name: 'Redox Reactions' },
      { binaryCode: '000010', name: 'Structure of Atom' },
      { binaryCode: '000011', name: 'Classification of Elements and Periodicity' },
      { binaryCode: '000100', name: 'Chemical Bonding and Molecular Structure' },
      { binaryCode: '000101', name: 'Solutions' },
      { binaryCode: '000110', name: 'Thermodynamics' },
      { binaryCode: '000111', name: 'Equilibrium' },
      { binaryCode: '001000', name: 'Electrochemistry' },
      { binaryCode: '001001', name: 'Chemical Kinetics' },
      { binaryCode: '001010', name: 'Organic Chemistry – IUPAC Nomenclature' },
      { binaryCode: '001011', name: 'Organic Chemistry – Isomerism' },
      { binaryCode: '001100', name: 'Organic Chemistry – GOC' },
      { binaryCode: '001101', name: 'Hydrocarbons' },
      { binaryCode: '001110', name: 'Haloalkanes and Haloarenes' },
      { binaryCode: '001111', name: 'Alcohols, Phenols and Ethers' },
      { binaryCode: '010000', name: 'Aldehydes, Ketones and Carboxylic Acids' },
      { binaryCode: '010001', name: 'Amines' },
      { binaryCode: '010010', name: 'Biomolecules' },
      { binaryCode: '010011', name: 'Purification and Analysis of Organic Compounds' },
      { binaryCode: '010100', name: 'Coordination Compounds' },
      { binaryCode: '010101', name: 'The p-Block Elements' },
      { binaryCode: '010110', name: 'The d- and f-Block Elements' },
      { binaryCode: '010111', name: 'Salt Analysis' },
      { binaryCode: '011000', name: 'p-Block Elements (Group 13 & 14)' },
      { binaryCode: '011001', name: 'The p-Block Elements (XII)' },
    ],
  },
];

export const getSubjectById = (id: string) => QUIZ_SUBJECTS.find(s => s.id === id);
    